outstack:
    domainOwner: cloudimpl
    domainContext: example
    apiContext: example
    cluster:
      servicePort: 12000
      gossipPort: 14000
  #    seedName: localhost
      seeds:
          - 192.168.1.3:13000
    providers:
      com.cloudimpl.outstack.collection.CollectionProvider:
          - name : MemCollection
            impl: com.cloudimpl.outstack.collection.MemCollectionProvider
            
          - name:  com.cloudimpl.outstack.collection.CollectionProvider
            impl: com.cloudimpl.outstack.collection.AwsCollectionProvider
            status: active
            configs:
              endpoint: http://localhost:1234
              leaderTable : LeaderTable 
      com.cloudimpl.outstack.runtime.EventRepositoryFactory:
          - name: MemRepositoryFactory
            impl: com.cloudimpl.outstack.runtime.repo.MemEventRepositoryFactory
            
          - name: DynamodbRepositoryFactory
            impl: com.cloudimpl.outstack.spring.repo.DynamodbRepositoryFactory
            status: active
            configs:
                endpoint: http://localhost:8000
                region: US_EAST_1
                defaultTable: commandTable
                UserTable: userTable
spring:
  main:
    web-application-type: reactive
#  thymeleaf:
#    cache: false  
#    check-template: true
#    check-template-location: true
#    content-type: text/html
#    enabled: true
#    encoding: UTF-8
#    mode: HTML
#    prefix: classpath:/templates/
#    suffix: .html  

server:
  error:
    include-message: always
  port: 15000
  
