apiVersion: com.cloudimpl.domainspec/v1
kind: Command
metadata:
  namespace: com.xventure.projectA
spec:
  - template:
      metadata:
        type: UserCreateRequest
        module: user
        name: user 
      fieldRefs:
        - name: id
          metadata:
            maxLen : 20
            minLen : 10
        - name
        - firstname
        - userId
        - orderType
        - address
