apiVersion: com.cloudimpl.domainspec/v1
kind: Entity
metadata:
  namespace: com.restrata.platform
spec:
  - template:
      metadata:
        type: Organization
        name: Organization 
        plural: organizations
        version: V1
        id: orgName
        tenant: false
      fieldRefs:
        - name: orgName
          metadata:
            maxLen : 25
            minLen : 10
        - website
      logic:
        - apply:
            evt: OrganizationCreated
            stmt:
               - this.website = evt.website
  - template:
      metadata:
        type: Tenant
        name: tenant 
        plural: tenants
        id: tenantName
        rootEntity: Organization
      fieldRefs:
        - endpoint
      logic:
        - apply:
            evt: TenantCreated
            stmt:
               - this.endpoint = evt.endpoint