apiVersion: com.cloudimpl.domainspec/v1
kind: Event
metadata:
  namespace: com.restrata.platform.events
spec:
  - template:
     metadata:
       type: OrganizationCreated
       owner: Organization
     fieldRefs:
       - website
  - template:
     metadata:
       type: TenantCreated
       owner: Tenant
     fieldRefs:
       - endpoint