apiVersion: com.cloudimpl.domainspec/v1
kind: Type
metadata:
  namespace: com.xventure.projectA
spec:
  - template:
      metadata:
        name: OrderType
        type: enum
        module: enums
      values:
        - MARKET
        - LIMIT
        - PEG
        - IOC
  - template:
      metadata:
        name: Address
        type: object
        module: value
      values:
        - streetNo
        - zipCode
        - postalCode

