outstack:
    domainOwner: cloudimpl
    domainContext: gateway
    apiContext: gateway
    cluster:
      servicePort: 11000
      gossipPort: 13000
    apiGateway:
      authEndpoint:
        domainOwner: cloudimpl
        domainContext: example
        version: version
        serviceName: UserService
    oauth:
        token:
            issuer: http://www.cloudimpl.com
        errorPageUri: /login
    providers:
      com.cloudimpl.outstack.collection.CollectionProvider:
          - name : MemCollection
            impl: com.cloudimpl.outstack.collection.MemCollectionProvider
            
          - name:  com.cloudimpl.outstack.collection.CollectionProvider
            impl: com.cloudimpl.outstack.collection.AwsCollectionProvider
            status: active
            configs:
              endpoint: http://localhost:1234
              leaderTable : LeaderTable 
      com.cloudimpl.outstack.runtime.EventRepositoryFactory:
          - name: MemRepositoryFactory
            impl: com.cloudimpl.outstack.runtime.repo.MemEventRepositoryFactory
            
          - name: DynamodbRepositoryFactory
            impl: com.cloudimpl.outstack.spring.repo.DynamodbRepositoryFactory
            status: active
            configs:
                endpoint: http://localhost:8000
                region: US_EAST_1
                defaultTable: commandTable
                UserTable: userTable

spring:
  main:
    web-application-type: reactive
    
server:
  error:
    include-message: always
  port: 20000
    